//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Inwoner.java
//  @ Date : 23/03/2017
//  @ Author : 
//
//




public class Inwoner {
	private Object naam;
}
