//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Schrikbaar.java
//  @ Date : 23/03/2017
//  @ Author : 
//
//




public interface Schrikbaar {
	public void reageerOpUitbarsting();
}
