//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Zoogdier.java
//  @ Date : 23/03/2017
//  @ Author : 
//
//




public class Zoogdier extends Inwoner implements EilandBewoner {
	public void reageerOpUitbarsting();
}
